spring:
  application:
    name: server

  config:
    import: optional:file:./.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

jwt:
  secret: ${JWT_SECRET}
  access-expire: ${JWT_ACCESS_TOKEN_EXPIRE_MS}
  refresh-expire: ${JWT_REFRESH_TOKEN_EXPIRE_MS}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
      voice-path: voice
      presigned-expire-seconds: 600
    region:
      static: ${AWS_REGION}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always